### ISSUE TITLE
IPFS Microgrant + per-project payouts

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#186]
Maybe we could apply for one of these for the upcoming IPFS work: https://github.com/ipfs/devgrants/blob/master/MICROGRANTS.md

A general question/problem, which came up a few times already, is how we can reward contributions to specific parts of the project, e.g. only Kredits or only Chat, or in this case only IPFS-related work.

**Comment by skddc** [comment]
I just had a quick thought: what if, instead of payouts per project, it works the other way around? As in, the dividend payout would draw from project-specific vaults, according to how much was done for that project? This way, you could still work on anything you want, but if too much work would be done on things that there's no budget for, then everybody would earn less. Thus giving contributors an incentive to get the right vaults filled for things they deem important, while donors/customers can meaningfully signal their preferences and priorities as well.

**Comment by bumi** [comment]
I like the general idea!
I am just a bit concerned about the complexity to implement it and would first want to have the reimbursements and a normal vault running. :)

**Comment by skddc** [comment]
Yes, the comment is not about planning priorities, and is completely separate of reimbursements. It is purely about the design of contributor dividends per project.

**Comment by skddc** [comment]
... also, the same as for reimbursements still applies: we can try the concepts with zero contract implementation first, to validate it and see what the implementation would actually require.
